name: GitHub Classroom Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
           python-version: 3.9.1

      - name: Install
        run: |
            pip install .
            pip install -r requirements_dev.txt

      - name: Dir
        run: |
            ll
      
      - name: Run tests
        run: |
            pytest .

      - name: Deploy project
        uses: ashishkujoy/render-deploy@v1.0.5
        with:
          service-id: srv-ck417o36fquc73fopttg
          service-key: ZmdcdpWHkoI
          api-key: rnd_IoSSfQ8iiO4DENQ0pTwybOgiHcUq
          max-deployment-wait-ms: 3600000
          delay-in-ms: 10000
   

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: postman/[inst] Lab1.postman_collection.json
          environment: postman/[inst][heroku] Lab1.postman_environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - name: Autograding
        uses: education/autograding@v1
        continue-on-error: true

#      - name: Github auto grader mark
#        uses: Romanow/google-sheet-autograder-marker@v1.0
#        with:
#          google_token: ${{secrets.GOOGLE_API_KEY}}
#          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
#          homework_number: 1
#          user_column: 'D'
#          column_offset: 'F'
#          mark: "'+"